// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx3JLT6aJ1MZhbxolKJLEHJ3e3o_m09Ck',
    appId: '1:471715673358:web:5b9230735d5409d18c535f',
    messagingSenderId: '471715673358',
    projectId: 'flash-chat-7a1cb',
    authDomain: 'flash-chat-7a1cb.firebaseapp.com',
    storageBucket: 'flash-chat-7a1cb.appspot.com',
    measurementId: 'G-7C7G0ZSG85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjd0PfhEt83xDJBXGhYKzZKDBmSqg-ns',
    appId: '1:471715673358:android:613f41ace14425f38c535f',
    messagingSenderId: '471715673358',
    projectId: 'flash-chat-7a1cb',
    storageBucket: 'flash-chat-7a1cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqLXcAmTQs_0O-56U966n9vxoHw1m0ePQ',
    appId: '1:471715673358:ios:a67a0719800a0a7e8c535f',
    messagingSenderId: '471715673358',
    projectId: 'flash-chat-7a1cb',
    storageBucket: 'flash-chat-7a1cb.appspot.com',
    iosBundleId: 'co.labib.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqLXcAmTQs_0O-56U966n9vxoHw1m0ePQ',
    appId: '1:471715673358:ios:b8d727578f692ba18c535f',
    messagingSenderId: '471715673358',
    projectId: 'flash-chat-7a1cb',
    storageBucket: 'flash-chat-7a1cb.appspot.com',
    iosBundleId: 'com.example.flashchat.RunnerTests',
  );
}
